/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trzy;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author kamil
 */
public class TrzeciProgram extends javax.swing.JFrame {
    int przyciskWysokosc;
    int przyciskSzerokosc;

    /**
     * Creates new form TrzeciProgram
     */
    public TrzeciProgram() {
        initComponents();
        przyciskWysokosc = jButtonUciekajacyPrzycisk.getHeight();
        przyciskSzerokosc = jButtonUciekajacyPrzycisk.getWidth();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension rozmEkranu = kit.getScreenSize();
        setLocation(((rozmEkranu.width/2)-200), ((rozmEkranu.height/2)-140));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUciekajacyPrzycisk = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jLabelPowitanie1 = new javax.swing.JLabel();
        jLabelPowitanie2 = new javax.swing.JLabel();
        jLabelPowitanie3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonUciekajacyPrzycisk.setVisible(false);
        jButtonUciekajacyPrzycisk.setText("Uciekający przycisk.");
        jButtonUciekajacyPrzycisk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUciekajacyPrzyciskMouseEntered(evt);
            }
        });
        jButtonUciekajacyPrzycisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUciekajacyPrzyciskActionPerformed(evt);
            }
        });

        jButtonStart.setText("Zacznij zabawę!");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelPowitanie1.setText("Witaj w trzecim programie na NJPO 2.");

        jLabelPowitanie2.setText("Wyobraź sobie, że wszedłeś na stronę z złośliwymi reklamami i próbujesz ją zamknąć.");

        jLabelPowitanie3.setText("Jeśli chcesz poćwiczyć \"skll\" w zamykaniu takich reklam, kliknij w poniższy przycisk.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelPowitanie1)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelPowitanie3))
                            .addComponent(jLabelPowitanie2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonUciekajacyPrzycisk)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPowitanie1)
                .addGap(9, 9, 9)
                .addComponent(jLabelPowitanie2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPowitanie3)
                .addGap(18, 18, 18)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUciekajacyPrzycisk)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUciekajacyPrzyciskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUciekajacyPrzyciskActionPerformed
        jButtonUciekajacyPrzycisk.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, "Gratulację. Teraz możesz iść robić coś pożytecznego.");
        this.dispose();
    }//GEN-LAST:event_jButtonUciekajacyPrzyciskActionPerformed

    private void jButtonUciekajacyPrzyciskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUciekajacyPrzyciskMouseEntered
        jButtonUciekajacyPrzycisk.setLocation(new Random().nextInt(400-przyciskWysokosc), new Random().nextInt(300-przyciskSzerokosc));
    }//GEN-LAST:event_jButtonUciekajacyPrzyciskMouseEntered

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        jButtonUciekajacyPrzycisk.setVisible(false);
        if(jButtonStart.isSelected());
            jLabelPowitanie1.setVisible(false);
            jLabelPowitanie2.setVisible(false);
            jLabelPowitanie3.setVisible(false);
            jButtonStart.setVisible(false);
            jButtonUciekajacyPrzycisk.setVisible(true);
    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrzeciProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrzeciProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrzeciProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrzeciProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrzeciProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonUciekajacyPrzycisk;
    private javax.swing.JLabel jLabelPowitanie1;
    private javax.swing.JLabel jLabelPowitanie2;
    private javax.swing.JLabel jLabelPowitanie3;
    // End of variables declaration//GEN-END:variables
}
