/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cztery;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author kamil
 */
public class CzwartyProgram extends javax.swing.JFrame {

    /**
     * Creates new form CzwartyProgram
     */
    public CzwartyProgram() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension rozmEkranu = kit.getScreenSize();
        setLocation(((rozmEkranu.width/2)-200), ((rozmEkranu.height/2)-140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserOtworzPlik = new javax.swing.JFileChooser();
        jFileChooserZapiszPlik = new javax.swing.JFileChooser();
        jLabelPowitanie = new javax.swing.JLabel();
        jLabelPesel = new javax.swing.JLabel();
        jTextFieldPesel = new javax.swing.JTextField();
        jLabelPoprawnosc = new javax.swing.JLabel();
        jButtonPoprawnosc = new javax.swing.JButton();
        jButtonZapisz = new javax.swing.JButton();
        jButtonOtwor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPesele = new javax.swing.JTextArea();
        jLabelInfoPesele = new javax.swing.JLabel();

        jFileChooserZapiszPlik.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPowitanie.setText("Witaj w czwartym programie na NJPO 2.");

        jLabelPesel.setText("Proszę podać PESEL:");

        jTextFieldPesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeselActionPerformed(evt);
            }
        });

        jLabelPoprawnosc.setText("Poprawność numeru PESEL:");

        jButtonPoprawnosc.setText("Sprawdź");
        jButtonPoprawnosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoprawnoscActionPerformed(evt);
            }
        });

        jButtonZapisz.setText("Zapisz");
        jButtonZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapiszActionPerformed(evt);
            }
        });

        jButtonOtwor.setText("Otwórz");
        jButtonOtwor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtworActionPerformed(evt);
            }
        });

        jTextAreaPesele.setColumns(20);
        jTextAreaPesele.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPesele);

        jLabelInfoPesele.setText("Wyszukaj twój plik tekstowy z PESElami by móc podejrzeć PESELE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelPowitanie))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPesel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPoprawnosc)
                            .addComponent(jButtonOtwor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPoprawnosc)
                            .addComponent(jButtonZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoPesele))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPowitanie)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesel)
                    .addComponent(jTextFieldPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoprawnosc)
                    .addComponent(jButtonPoprawnosc))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZapisz)
                    .addComponent(jButtonOtwor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelInfoPesele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPoprawnoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoprawnoscActionPerformed
        PESEL.sprawdzPESEL(jTextFieldPesel.getText());
    }//GEN-LAST:event_jButtonPoprawnoscActionPerformed

    private void jTextFieldPeselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeselActionPerformed

    private void jButtonOtworActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtworActionPerformed
        int odpowiedz = jFileChooserOtworzPlik.showOpenDialog(this);
        if (odpowiedz == jFileChooserOtworzPlik.APPROVE_OPTION) {
            File file = jFileChooserOtworzPlik.getSelectedFile();
            try {
                jTextAreaPesele.read(new FileReader(file.getAbsolutePath()), null); 
            } catch (IOException e) {
                System.out.println("Nie mogę otworzyć pliku:" +file.getAbsolutePath());
                System.out.println("Problem:" + e);
             }
        }
    }//GEN-LAST:event_jButtonOtworActionPerformed

    private void jButtonZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapiszActionPerformed
        int odpowiedz = jFileChooserZapiszPlik.showOpenDialog(this);
        if (odpowiedz == jFileChooserZapiszPlik.APPROVE_OPTION) {
            File file = jFileChooserZapiszPlik.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file);
                String text = jTextAreaPesele.getText();
                out.write(text.replaceAll("\n", System.getProperty("line.separator")));
                out.close();
            } catch (IOException e) {
                System.out.println("Nie mogę zapisać pliku:" +file.getAbsolutePath());
                System.out.println("Problem:" + e);
             }
        }
    }//GEN-LAST:event_jButtonZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CzwartyProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CzwartyProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CzwartyProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CzwartyProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CzwartyProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtwor;
    private javax.swing.JButton jButtonPoprawnosc;
    private javax.swing.JButton jButtonZapisz;
    private javax.swing.JFileChooser jFileChooserOtworzPlik;
    private javax.swing.JFileChooser jFileChooserZapiszPlik;
    private javax.swing.JLabel jLabelInfoPesele;
    private javax.swing.JLabel jLabelPesel;
    private javax.swing.JLabel jLabelPoprawnosc;
    private javax.swing.JLabel jLabelPowitanie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPesele;
    private javax.swing.JTextField jTextFieldPesel;
    // End of variables declaration//GEN-END:variables
}
