/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dwa;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kamil
 */
public class DrugiProgram extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DrugiProgram() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension rozmEkranu = kit.getScreenSize();
        setLocation(((rozmEkranu.width/2)-200), ((rozmEkranu.height/2)-140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jLabelInfo2 = new javax.swing.JLabel();
        jLabelPierwszaLb = new javax.swing.JLabel();
        jLabelDrugaLb = new javax.swing.JLabel();
        jTextFieldPierwszaLb = new javax.swing.JTextField();
        jTextFieldDrugaLb1 = new javax.swing.JTextField();
        jRadioButtonDodawanie = new javax.swing.JRadioButton();
        jRadioButtonOdejmowanie = new javax.swing.JRadioButton();
        jRadioButtonMnozenie = new javax.swing.JRadioButton();
        jRadioButtonDzielenie = new javax.swing.JRadioButton();
        jButtonWyjscie = new javax.swing.JButton();
        jLabelWynik = new javax.swing.JLabel();
        jTextFieldWynik = new javax.swing.JTextField();
        jButtonLicz = new javax.swing.JButton();
        jButtonCzysc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfo.setText("Witaj w drugim programie GUI na NJPO2.");

        jLabelInfo2.setText("Prosty kalkulator");

        jLabelPierwszaLb.setText("Pierwsza liczba:");

        jLabelDrugaLb.setText("Druga liczba:");

        jTextFieldPierwszaLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPierwszaLbActionPerformed(evt);
            }
        });

        jTextFieldDrugaLb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDrugaLb1ActionPerformed(evt);
            }
        });

        jRadioButtonDodawanie.setText("Dodawanie");
        jRadioButtonDodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDodawanieActionPerformed(evt);
            }
        });

        jRadioButtonOdejmowanie.setText("Odejmowanie");
        jRadioButtonOdejmowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOdejmowanieActionPerformed(evt);
            }
        });

        jRadioButtonMnozenie.setText("Mnożenie");
        jRadioButtonMnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMnozenieActionPerformed(evt);
            }
        });

        jRadioButtonDzielenie.setText("Dzielenie");
        jRadioButtonDzielenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDzielenieActionPerformed(evt);
            }
        });

        jButtonWyjscie.setText("Wyjście z programu");
        jButtonWyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWyjscieActionPerformed(evt);
            }
        });

        jLabelWynik.setText("Wynik");

        jTextFieldWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWynikActionPerformed(evt);
            }
        });

        jButtonLicz.setText("Licz");
        jButtonLicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczActionPerformed(evt);
            }
        });

        jButtonCzysc.setText("Wyczyść dane");
        jButtonCzysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCzyscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonMnozenie)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButtonDzielenie))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonDodawanie)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOdejmowanie)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonWyjscie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLicz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCzysc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDrugaLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPierwszaLb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDrugaLb1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPierwszaLb, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelWynik)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabelInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfo2)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabelInfo2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPierwszaLb)
                            .addComponent(jTextFieldPierwszaLb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDrugaLb)
                            .addComponent(jTextFieldDrugaLb1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelWynik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDodawanie)
                            .addComponent(jRadioButtonOdejmowanie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMnozenie)
                            .addComponent(jRadioButtonDzielenie))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLicz)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCzysc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonWyjscie)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPierwszaLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPierwszaLbActionPerformed
        JTextField pierwszalb = new javax.swing.JTextField();
    }//GEN-LAST:event_jTextFieldPierwszaLbActionPerformed

    private void jTextFieldDrugaLb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDrugaLb1ActionPerformed
        JTextField drugalb = new javax.swing.JTextField();
    }//GEN-LAST:event_jTextFieldDrugaLb1ActionPerformed

    private void jButtonWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWyjscieActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButtonWyjscieActionPerformed

    private void jRadioButtonDodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDodawanieActionPerformed
 
        
        if(jRadioButtonOdejmowanie.isSelected()) jRadioButtonOdejmowanie.setSelected(false);
        if(jRadioButtonMnozenie.isSelected()) jRadioButtonMnozenie.setSelected(false); 
        if(jRadioButtonDzielenie.isSelected()) jRadioButtonDzielenie.setSelected(false);
        if(jRadioButtonDodawanie.isSelected()) jRadioButtonDodawanie.setSelected(true);
       
    }//GEN-LAST:event_jRadioButtonDodawanieActionPerformed

    private void jRadioButtonOdejmowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOdejmowanieActionPerformed
        
        if(jRadioButtonOdejmowanie.isSelected()) jRadioButtonOdejmowanie.setSelected(true);
        if(jRadioButtonMnozenie.isSelected())    jRadioButtonMnozenie.setSelected(false); 
        if(jRadioButtonDzielenie.isSelected())   jRadioButtonDzielenie.setSelected(false);
        if(jRadioButtonDodawanie.isSelected())   jRadioButtonDodawanie.setSelected(false);
       
    }//GEN-LAST:event_jRadioButtonOdejmowanieActionPerformed

    private void jRadioButtonMnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMnozenieActionPerformed
       
        if(jRadioButtonOdejmowanie.isSelected()) jRadioButtonOdejmowanie.setSelected(false);
        if(jRadioButtonMnozenie.isSelected())    jRadioButtonMnozenie.setSelected(true); 
        if(jRadioButtonDzielenie.isSelected())   jRadioButtonDzielenie.setSelected(false);
        if(jRadioButtonDodawanie.isSelected())   jRadioButtonDodawanie.setSelected(false);
    }//GEN-LAST:event_jRadioButtonMnozenieActionPerformed

    private void jRadioButtonDzielenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDzielenieActionPerformed
        
        if(jRadioButtonOdejmowanie.isSelected()) jRadioButtonOdejmowanie.setSelected(false);
        if(jRadioButtonMnozenie.isSelected())    jRadioButtonMnozenie.setSelected(false); 
        if(jRadioButtonDzielenie.isSelected())   jRadioButtonDzielenie.setSelected(true);
        if(jRadioButtonDodawanie.isSelected())   jRadioButtonDodawanie.setSelected(false);
    }//GEN-LAST:event_jRadioButtonDzielenieActionPerformed

    private void jTextFieldWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWynikActionPerformed
        jTextFieldWynik.setEditable(false);
    }//GEN-LAST:event_jTextFieldWynikActionPerformed
    
    private double getLiczba(JTextField jtf) throws NumberFormatException {
        return Double.parseDouble(jtf.getText());
    }
    private void jButtonLiczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczActionPerformed
        
        String nazwa = "";
        try {
            nazwa = "pierwszalb";
            double pierwszalb = getLiczba(jTextFieldPierwszaLb);
            nazwa = "drugalb";
            double drugalb = getLiczba(jTextFieldDrugaLb1);
            
        if(jRadioButtonDodawanie.isSelected())
            jTextFieldWynik.setText((double)Math.round(1000*(pierwszalb + drugalb))/1000 + "");
        else if(jRadioButtonOdejmowanie.isSelected())
            jTextFieldWynik.setText((double)Math.round(1000*(pierwszalb - drugalb))/1000 + "");
        else if(jRadioButtonMnozenie.isSelected())
            jTextFieldWynik.setText((double)Math.round(1000*(pierwszalb * drugalb))/1000 + "");
        else if(jRadioButtonDzielenie.isSelected())
            if(drugalb != 0)
                jTextFieldWynik.setText((double)Math.round(1000*(pierwszalb / drugalb))/1000 + "");
            else
                JOptionPane.showMessageDialog(rootPane, "Nie dziel przez zero cholero!");
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Podaj poprawną liczbę!");
        }        
    }//GEN-LAST:event_jButtonLiczActionPerformed

    private void jButtonCzyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCzyscActionPerformed
        jTextFieldPierwszaLb.setText(" ");
        jTextFieldDrugaLb1.setText(" ");
        jTextFieldWynik.setText(" ");
    }//GEN-LAST:event_jButtonCzyscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrugiProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrugiProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrugiProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrugiProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrugiProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCzysc;
    private javax.swing.JButton jButtonLicz;
    private javax.swing.JButton jButtonWyjscie;
    private javax.swing.JLabel jLabelDrugaLb;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo2;
    private javax.swing.JLabel jLabelPierwszaLb;
    private javax.swing.JLabel jLabelWynik;
    private javax.swing.JRadioButton jRadioButtonDodawanie;
    private javax.swing.JRadioButton jRadioButtonDzielenie;
    private javax.swing.JRadioButton jRadioButtonMnozenie;
    private javax.swing.JRadioButton jRadioButtonOdejmowanie;
    private javax.swing.JTextField jTextFieldDrugaLb1;
    private javax.swing.JTextField jTextFieldPierwszaLb;
    private javax.swing.JTextField jTextFieldWynik;
    // End of variables declaration//GEN-END:variables
}
